> ## Make a copy of this notebook (File menu -> Make a Copy...)

### Homework Question 1

By giving examples, explain all meanings of the `@` operator we covered in lab. You may use the examples from the lab. You should include both code and text explanation.

In [52]:
import numpy as np

# Define arrays as used in the lab
v = np.array([5,3,-2])
w = np.array([1,5,-1])
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[3,1,1],[2,2,4],[5,7,1]])

# Using the @ operator on two same-length vectors returns a scalar equal to the sum of the piecewise multiplied vectors
print(v@w)
print((v@w) == np.sum(v*w), end="\n\n")

# Using the @ operator on a vector and a matrix with column length or row length equal to the vector's size
# When a matrix is first it uses a vector as a column and returns a vector with indices equal to the matrix rows * vector
print(A@v)
# When a vector is first it uses a vector as a row and returns a vector with indices equal to the vector * matrix cols
print(v@A, end="\n\n")

# Using the @ operator on two matrices under the condition M1.row_length == M2.col_length
# The operation treats each row in M1 as a vector as above and creates a 2d array.
print(A@B, end="\n\n")
print(B@A)

22
True

[ 5 23 41]
[ 3  9 15]

[[22 26 12]
 [52 56 30]
 [82 86 48]]

[[14 19 24]
 [38 46 54]
 [40 53 66]]


### Homework Question 2

Explain how Questions 3 and 6 from the lab demonstrate the *column* and *row* pictures of matrix multiplication respectively. Be sure to use the terms *dot product* and *linear combination* in your answer. Again, use both text and code.

In [55]:
# 3. The column picture
# In this problem we find the value of the dot product of A and B in three different ways
# The first way we use numpy's built in operand
# In the second we use the row representation of A and break down B into its column vectors then form an array of 
#     the dot products between the rows of A and the cols of B. This is similar to in class when we expanded Ax to 
#     a system of linear equations.
# In the last method we break down A into columns and multiply them by scalars in B. This form shows the solution to the dot
#     product as a matrix of linear combinations of A where the scalars are taken from B.
print(A@B)
print(np.array([A@B[:,0], A@B[:,1], A@B[:,2]]).T)
c1 = B[0,0]*A[:,0] + B[1,0]*A[:,1] + B[2,0]*A[:,2]
c2 = B[0,1]*A[:,0] + B[1,1]*A[:,1] + B[2,1]*A[:,2]
c3 = B[0,2]*A[:,0] + B[1,2]*A[:,1] + B[2,2]*A[:,2]
print(np.array([ c1,c2,c3 ]).T, end="\n\n")

# 6. The row picture
# In order to find the value of (1,2) in the dot product matrix, we took one row of A and multiplied it by a column of B.
# This interpretation of a dot product describes each element as a product of a row of A and a col from B.
C = A @ B
print(C[1,2])
print(A[1] @ B[:,2])

[[22 26 12]
 [52 56 30]
 [82 86 48]]
[[22 26 12]
 [52 56 30]
 [82 86 48]]
[[22 26 12]
 [52 56 30]
 [82 86 48]]

30
30


### Homework Question 3

Submit your answers to Question 10 from the lab. You should typeset all matrices in LaTeX as part of your text below. Be sure to write complete sentences and full explanations.

Catherine is in Cowdogs;
DeDreana is in Bearcats and Skunkpossums;
Eimid is in all three organizations;
Filipe is in Bearcats and Cowdogs;
Galia is in Skunkpossums;
Homer is in Bearcats and Skunkpossums.

### 1. Membership Matrix
#### A = $\begin{bmatrix}
1&0&0\\
0&1&1\\
0&1&0\\
1&0&1\\
1&1&1\\
1&1&0\\
0&0&1\\
1&0&1
\end{bmatrix}$
### 2. $A^TA$
  1. 3x3 <br><br>

  1. The rows/columns represent the organizations and their membership<br><br>

  1. Compute the matrix by hand.<br><br>
      #### ATxA = $\begin{bmatrix}
1&0&0&1&1&1&0&1\\ 
0&1&1&0&1&1&0&0\\ 
0&1&0&1&1&0&1&1
\end{bmatrix} * \begin{bmatrix}
1&0&0\\
0&1&1\\
0&1&0\\
1&0&1\\
1&1&1\\
1&1&0\\
0&0&1\\
1&0&1
\end{bmatrix}= \begin{bmatrix}
5&2&3\\ 2&4&2\\ 3&2&5
\end{bmatrix}$<br><br>

  1. The numbers on the diagonal represent the ith organizaion's total membership. The diagonals represent the sum when we multiplied an organizations membership vector by itself. Therefore it is the sum of each member in the organization. <br><br>
  
  1. The $(i,j)$ entries represent the amount of members that are in both organizations i and j. These entries represent multiplying the membership vector of one organization by another, this results in a sum of the vectors multiplied. It is the same as treating the vectors as bit strings and summing the result of an & operation.<br><br>
  
  1. They are the same because vector multiplication is commutative.<br><br>

### 3. $AA^T$
  1. 8x8 <br><br>

  1. The rows/columns represent people and the organizations that they are associated with<br><br>

  1. Compute the matrix by hand.<br><br>
      #### ATxA = $\begin{bmatrix}
1&0&0\\
0&1&1\\
0&1&0\\
1&0&1\\
1&1&1\\
1&1&0\\
0&0&1\\
1&0&1
\end{bmatrix} * \begin{bmatrix}
1&0&0&1&1&1&0&1\\ 
0&1&1&0&1&1&0&0\\ 
0&1&0&1&1&0&1&1
\end{bmatrix} = \begin{bmatrix}
1&0&0&1&1&1&0&1\\ 
0&2&1&1&2&1&1&1\\ 
0&1&1&0&1&1&0&0\\ 
1&1&0&2&2&1&1&2\\ 
1&2&1&2&3&2&1&2\\ 
1&1&1&1&2&2&0&1\\ 
0&1&0&1&1&0&1&1\\ 
1&1&0&2&2&1&1&2\end{bmatrix}$<br><br>

  1. The numbers on the diagonal represent the ith person's total membership. During calculation, the diagonals represent the sum when we multiplied an persons membership vector by itself. Therefore it is the sum of each organization that a person is enrolled in. <br><br>
  
  1. The $(i,j)$ entries represent shared organizations between person i and j. These entries represent multiplying the membership vector of one person by another, this results in a sum of the vectors multiplied. As before, this operation is the same as treating the vectors as bit strings and summing the result of an & operation.<br><br>
  
  1. Again, they are the same because vector multiplication is commutative.<br><br>

### Homework Question 4

Other than Paul Revere, pick one of the central actors identified at the end of the lab. Do some research on that person and submit a paragraph describing them and their role in the Revolutionary War. Submit this in the last textbox below, again using Markdown to format your answers. Be sure to cite your sources!

<p> Samuel Adams was a key actor in the Revolutionary War. He originally protested the British taxation system which was imposed upon the American Colonies, for example the Stamp Act. He pushed for the colonies to unite and form a government, which happened in 1774. Adams had been actively publishing articles against the British rule, following the ideas of John Locke regarding individual freedoms. A letter, titled “Massachusetts Circular Letter” led to the boycott of British goods. The British imposition of tax on tea (known as the Tea Act), led to Adams and his underground political group, the Sons of Liberty to start ‘The Boston Tea Party’. Adams had helped spark the Revolutionary War along with his fellow agitators, and spent much of the war focusing on organising and establishing the way the new government would work. Source: https://www.history.com/topics/american-revolution/samuel-adams</p>

### Homework Question 5

Explain what the following code does, then rewrite it in a more NumPy-ish way. See Lab 1 for hints! You should be able to get the same result with one line of code! Test your code by taking any $4\times 5$ matrix and checking that your code and this routine give the same answer on it.

```python
def addrows(A):
    rows,cols = A.shape
    
    rowsum = np.zeros(rows)
    
    for row in range(rows):
        for col in range(cols):
            rowsum[row] += A[row,col]
    
    return rowsum
```

In [59]:
A= np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(A.sum(axis = 1)*1.0)
B = A.astype(float).sum(axis=1)
print(B)

[ 6. 15. 24.]


### Homework Question 6

Write routines that take a matrix and return results as follows. It is also perfectly fine (perhaps better!) to give single lines of code that achieve the same result instead of routines. This is possible with all these, but much easier for second and third than the first.

* *swaprows(A,i,j)* should take an array and return the same array, but with rows *i* and *j* swapped.
* *rowmult(A,i,c)* should take an array, a row number *i* and a constant *c*, and return the same array, but with row *i* multiplied by *c*.
* *rowaddmult(A,i,j,c)* should take an array, row numbers *i* and *j*, and a constant *c*, and return the same array, but with *c* multiplied by row *i* added to row *j*.

As always, show examples of your code. Use a $4\times 5$ array of your choice.

> **Note:** We will use these routines/lines of code extensively in the coming labs. Get them right!

In [49]:
#intialize sample 4 x 5 array to work with
A = np.arange(20).reshape((4,5))

#function to swap two rows given matrix and indices 
def swaprows(A,i,j): 
    A[[i,j]] = A[[j,i]]  #swap rows 
    return A

#function to mutliply row of matrix A by scalar 
def rowmult(A,i,c):
    A[i] = c * A[i] #scalar multiplication 
    return A

#function to add mutliple (c) of row i to row j of matrix A
def rowaddmult(A,i,j,c):
    temp = c * A[i]    #store row to be added 
    A[j] += temp       #perform row replacement
    return A
    
print(swaprows(A,1,2))
print(rowmult(A,1,11))
print(rowaddmult(A,1,-1,20))
    

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [-1 -1  0  1  1]]

Swap rows 1 and 4
[[-1 -1  0  1  1]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [ 1  2  3  4  5]]

Multiply row 2 by 10
[[-1 -1  0  1  1]
 [40 50 60 70 80]
 [ 7  8  9 10 11]
 [ 1  2  3  4  5]]

Add 5 times row 0 to row 1
[[-1 -1  0  1  1]
 [35 45 60 75 85]
 [ 7  8  9 10 11]
 [ 1  2  3  4  5]]

