> ## Make a copy of this notebook (File menu -> Make a Copy...)

### Homework Question 1
Consider the same situation as in Question 15 from the lab, but on a pentagon instead of a square. That is, there are five corners instead of four. Show that the corresponding Markov chain is not periodic, and that its transition matrix is regular.

#### Not Periodic ####
A state in a Markov chain has period k if any return to it must occur in multiples of k steps. With a pentagon, going in a full circle to return to the original point produces an odd number of steps. On the other hand, going forward one step and backward one step (an even number of steps) will also return you to the original point. Therefore, any return to the original point does not occur in multiples of k steps.

#### Regular ####
Over time, there is a chance that you can be at any corner of the pentagon (since returning to a point doesn't depend on cycles). A^n contains non-zero entries for some n, as seen below.

In [2]:
import numpy as np
pentagon = np.array([[0,0.5,0,0,0.5],[0.5,0,0.5,0,0],[0,0.5,0,0.5,0],[0,0,0.5,0,0.5],[0.5,0,0,0.5,0]])
for i in range(1,21):
    print(np.linalg.matrix_power(pentagon,i))

[[0.  0.5 0.  0.  0.5]
 [0.5 0.  0.5 0.  0. ]
 [0.  0.5 0.  0.5 0. ]
 [0.  0.  0.5 0.  0.5]
 [0.5 0.  0.  0.5 0. ]]
[[0.5  0.   0.25 0.25 0.  ]
 [0.   0.5  0.   0.25 0.25]
 [0.25 0.   0.5  0.   0.25]
 [0.25 0.25 0.   0.5  0.  ]
 [0.   0.25 0.25 0.   0.5 ]]
[[0.    0.375 0.125 0.125 0.375]
 [0.375 0.    0.375 0.125 0.125]
 [0.125 0.375 0.    0.375 0.125]
 [0.125 0.125 0.375 0.    0.375]
 [0.375 0.125 0.125 0.375 0.   ]]
[[0.375  0.0625 0.25   0.25   0.0625]
 [0.0625 0.375  0.0625 0.25   0.25  ]
 [0.25   0.0625 0.375  0.0625 0.25  ]
 [0.25   0.25   0.0625 0.375  0.0625]
 [0.0625 0.25   0.25   0.0625 0.375 ]]
[[0.0625  0.3125  0.15625 0.15625 0.3125 ]
 [0.3125  0.0625  0.3125  0.15625 0.15625]
 [0.15625 0.3125  0.0625  0.3125  0.15625]
 [0.15625 0.15625 0.3125  0.0625  0.3125 ]
 [0.3125  0.15625 0.15625 0.3125  0.0625 ]]
[[0.3125   0.109375 0.234375 0.234375 0.109375]
 [0.109375 0.3125   0.109375 0.234375 0.234375]
 [0.234375 0.109375 0.3125   0.109375 0.234375]
 [0.234375 0.234375 0.1093

### Homework Question 2
Consider a Markov chain with transition matrix given by the following code:
  ```python
  A= np.array([
               [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.5   ,  0.25  ],
               [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.5   ,  0.75  ],
               [ 0.5   ,  0.3333,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
               [ 0.25  ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
               [ 0.25  ,  0.6667,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
               [ 0.    ,  0.    ,  0.3333,  0.5   ,  0.75  ,  0.    ,  0.    ],
               [ 0.    ,  0.    ,  0.6667,  0.5   ,  0.25  ,  0.    ,  0.    ]])
   ```
  
1. Draw a state space diagram for this chain (use [this link](https://graphonline.ru/en/)). If you're having trouble putting the nodes and arrows in sensible places, you may want to do the rest of this question first.<br><br>
1. Show that this chain is periodic. What is the period?<br><br>
1. By again considering powers of this matrix, show that the seven nodes divide into three *cyclic classes*. That is, show that there are three subsets of nodes, $A$, $B$, and $C$, each with the property 'if we start at a node in a given class, we can only return to the class $p$ steps later, where $p$ is the period of the chain'. Numbering the nodes from 1 to 7, which nodes are in each cyclic class?<br><br>

### Question 1 ###
See GradeScope Attachment
### Question 2 ###
The period is 3. If we observe A^n, the transition matrix has zero entries over time, indicating that there are some vertices that we cannot return to from a given vertex. This is because to return to some vertices, it takes 3K steps. If we focus on one node, A, for example, we notice that only after every three powers does the probability for getting to A from A become positive. In other words, it always takes multiples of three steps for A to return to itself.

### Question 3 ###
If nodes A-G are numbered 1-7, we can say that nodes 1 and 2 belong to cyclic class A, 3-5 belong to B, and 6 and 7 belong to C. If we look at every third matrix power, that's the only time that for a given node, the probability of getting to the other nodes in its class is positive. In other words, given that we start at node 1, after the third matrix power, it is possible to reach node 1 or 2 (since the probability is positive), and so the nodes are in the same cyclic class.

In [4]:
A= np.array([
               [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.5   ,  0.25  ],
               [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.5   ,  0.75  ],
               [ 0.5   ,  0.3333,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
               [ 0.25  ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
               [ 0.25  ,  0.6667,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
               [ 0.    ,  0.    ,  0.3333,  0.5   ,  0.75  ,  0.    ,  0.    ],
               [ 0.    ,  0.    ,  0.6667,  0.5   ,  0.25  ,  0.    ,  0.    ]])
np.set_printoptions(precision=3)
for i in range(1,21):
    print(np.linalg.matrix_power(A,i))

[[0.    0.    0.    0.    0.    0.5   0.25 ]
 [0.    0.    0.    0.    0.    0.5   0.75 ]
 [0.5   0.333 0.    0.    0.    0.    0.   ]
 [0.25  0.    0.    0.    0.    0.    0.   ]
 [0.25  0.667 0.    0.    0.    0.    0.   ]
 [0.    0.    0.333 0.5   0.75  0.    0.   ]
 [0.    0.    0.667 0.5   0.25  0.    0.   ]]
[[0.    0.    0.333 0.375 0.438 0.    0.   ]
 [0.    0.    0.667 0.625 0.562 0.    0.   ]
 [0.    0.    0.    0.    0.    0.417 0.375]
 [0.    0.    0.    0.    0.    0.125 0.062]
 [0.    0.    0.    0.    0.    0.458 0.563]
 [0.479 0.611 0.    0.    0.    0.    0.   ]
 [0.521 0.389 0.    0.    0.    0.    0.   ]]
[[0.37  0.403 0.    0.    0.    0.    0.   ]
 [0.63  0.597 0.    0.    0.    0.    0.   ]
 [0.    0.    0.389 0.396 0.406 0.    0.   ]
 [0.    0.    0.083 0.094 0.109 0.    0.   ]
 [0.    0.    0.528 0.51  0.484 0.    0.   ]
 [0.    0.    0.    0.    0.    0.545 0.578]
 [0.    0.    0.    0.    0.    0.455 0.422]]
[[0.    0.    0.    0.    0.    0.386 0.395]
 [0.   

### Homework Question 3

For this question, you will write code that generates sensible random words that are (mostly) pronounceable in English. You will do this by creating a Markov chain whose nodes are letters in English words, and whose transition probabilities are given by analyzing a large set of existing English words.<br><br>

1. You will find a set of approximately 275,000 English words in the file *data/en.txt*. We will use this to figure out what the probability of a letter occuring in a word is, given the previous letter. For example, if the current letter is 'q', the next letter is 'u' with very high probability. Generate the transition matrix between all 26 states (a.k.a. English letters). Here are some code snippets that might help: 
```python
      # This opens the file and prints every line.
      f = open('data/en.txt')
      for word in f:
         print(word)

      # After you're done with a file, close it:
      f.close()

      # Each line has an extra character at the end (the endline character). The following code strips it:
      word = word.rstrip()

      # Strings can be accessed like one-dimensional arrays:
      for i in len(word):
         print(word[i])

      # The following function will return a number correponding to the letter input.
      # e.g. testletter('a') will return 0, and testletter('z') will return 25
      import string
      def let2num(letter):
          dictionary = {letter: index for index, letter in enumerate(string.ascii_lowercase)}
          return dictionary[letter]
```
After you've written your code, check the probabilities of different letters following 'q'. This is a good indicator that your code is correct!<br><br>
1. Since this is a large matrix, it would not be efficient to use our row-reduction code to find its eigenvalues and eigenvectors. Instead, we use a NumPy built-in function. By investigating the *np.linalg.eig(A)* function using its documentation, find the eigenvector corresponding to the eigenvalue 1 for your transition matrix. Scale it to ensure that its sum is 1!
> **Note: In general, eigenvalues and eigenvectors may be complex (i.e. contain numbers of the form $a+bi$, where $i=\sqrt{-1}$). The correct eigenvector here has no complex entries. Nonetheless, NumPy will represent the vector using its complex data type. After you're sure you have the right vector, you can cast it to real numbers by using `np.real(v)`.**
1. Explain why the entries of this eigenvector should be very close to the frequencies of each letter in the word set.<br><br>
1. Write code to check that this is indeed the case.<br><br>
1. What is the probability that the letter following 'q' is 'u'? Find some words in the list for which a letter other than 'u' follows a 'q'.<br><br>
1. Lastly, write a *namegen(n)* function that generates words of length $n$ using your transition matrix. You may find the following code snippets helpful:
```python
      # This returns a string containing all lowercase letters:
      import string
      string.ascii_lowercase

      # This returns a random number between 0 and 25, with probability distribution given by the vector v:
      np.random.choice(26,p=v)

      # You can add a letter to string as follows:
      mystring = 'co'
      mystring += 'w'
      mystring
```

Test out your code by generating words of different lengths. Are most of them pronounceable? Explain why they are not all pronounceable. 
  
  
**Extra Credit** Write down a few ideas that would increase the likelihood of pronounceable randomly generated words. Implement them in code.

In [123]:
# The following function will return a number correponding to the letter input.
# e.g. testletter('a') will return 0, and testletter('z') will return 25
import string
def let2num(letter):
    dictionary = {letter: index for index, letter in enumerate(string.ascii_lowercase)}
    return dictionary[letter]

#create freq = array to count frequencies of letters; rows = letter we're on
#cols = frequency of succeeding letter
#create prob = matrix of probabilities where rows is current letter and columns is succeeding
freq = np.zeros((26,26))
prob = np.zeros_like(freq)
f = open('data/en.txt')

#iterate through each word, iterate through each character, count frequencies of letters appearing
#after each other
for word in f:
    word = word.rstrip()
    for i in range(len(word)-1):
        letter = let2num(word[i])
        letterAfter = let2num(word[i+1])
        freq[letter,letterAfter] += 1
f.close()

for i in range(26):
    rowSum = np.sum(freq[i])
    prob[i] = freq[i]/rowSum

freq = freq.T
prob = prob.T

In [136]:
value, vector = np.linalg.eig(prob)
print("Eigenvalues: ")
print(np.real(value))
#eigenvalue of 1 is at index 0

print("1-Eigenvector Scaled to Sum to 1")
sum = np.sum(np.real(vector[:,0]))
print(np.real(vector[:,0])/sum)


#Question 3
#As the limit approaches infinity, the term with the eigenvalue of 1 dominates, and so we expect
#the probability ratios to mimic the one given by the 1-eigenvector. 
#Given no starting distribution, the probability of the next letter is just the frequency of each letter in
#the word set; the more frequent that letter has appeared, the greater the chance it will be the next 
#letter. Similar to the weather example, since the transition matrix is column stochastic,
#we are guaranteed a eigenvalue of 1, and the corresponding 1-eigenvector is a stationary distribution
#and the stationary distribution is the long-term probability distributions.

#Question 4
#It is indeed the case that the entries of the eigenvector is close the the freq of the word set
f = open('data/en.txt')
totalFreqs = np.zeros(26)
for word in f:
    word = word.rstrip()
    for char in word:
        letter = let2num(char)
        totalFreqs[letter] += 1
print(totalFreqs/np.sum(totalFreqs))
f.close()
print("They are indeed similar")



print("The probability that 'u' follows 'q': " + str(prob[let2num("u"),let2num("q")]))
q = []
f = open('data/en.txt')
for word in f:
    if "qu" in word:
        word = word.rstrip()
        q.append(word)
        if len(q) == 5:
            break
f.close()
print("Some words in which 'u' follows 'q': ")
print(q)

Eigenvalues: 
[ 1.    -0.419 -0.136 -0.136 -0.049 -0.049  0.08   0.08   0.115  0.086
  0.086 -0.088  0.085  0.065  0.065 -0.024 -0.024  0.038 -0.033 -0.033
 -0.012 -0.012  0.01   0.01  -0.002  0.007]
1-Eigenvector Scaled to Sum to 1
[0.076 0.013 0.036 0.03  0.123 0.008 0.027 0.024 0.097 0.001 0.008 0.052
 0.027 0.071 0.068 0.024 0.001 0.07  0.099 0.072 0.032 0.008 0.006 0.003
 0.018 0.005]
[0.077 0.018 0.04  0.033 0.113 0.012 0.028 0.025 0.091 0.002 0.009 0.052
 0.029 0.067 0.067 0.03  0.002 0.07  0.096 0.066 0.033 0.009 0.007 0.003
 0.016 0.005]
They are indeed similar
The probability that 'u' follows 'q': 0.9792560801144492
Some words in which 'u' follows 'q': 
['absquatulate', 'absquatulated', 'absquatulates', 'absquatulating', 'acequia']


In [119]:
def namegen(n):
    #empty string to build the name with
    name = ""
    
    #start with an equal chance of choosing any letter
    v = np.ones(26)/26

    for i in range(10):
        name += chr(np.random.choice(26,p=v) + 97) #ASCII shift by 97 to get a valid letter
        v = prob@v #get probability of next letter
    return name

for i in range(10):
    print(namegen(np.random.randint(4,8)))

#Most of them are not pronounceable because this implementation only considers one letter following
#another and fails to consider entire syllable clusters or position in the name/word itself. As such,
#we get some syllable clusters or syllable positions that are not permissible in English.

sycoladegr
posrarssuh
dyataerior
rueomlconl
ghrdtlrhgr
kllpdmatay
feetaynlrt
zhntcysrdf
zniaensafi
cserhotrco


In [ ]:
#Consider the previous two/three letters when deciding the letter after